name: Build Web & Deploy to GH
on: [push,pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Setup emsdk                 
        uses: mymindstorm/setup-emsdk@v10
        with:
          actions-cache-folder: 'emsdk-cache'

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          mkdir build
          cd build
          emcmake cmake .. -DPLATFORM=Web && cmake --build .
          mkdir website
          mv bin/SkyEmu.html bin/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/bin # The folder the action should deploy.
